### PR TITLE
Fixed small issue with magic file

### PR DESCRIPTION
**Pull request by DaGaMs**
This is a quick fix with a new magic.mgc file that fixes one wrong regex, see issue #102

### CODE REVIEW

**Comment by FranckDepoortere** [comment]
Hello, 
We have  the same issue, and your Magic.mgc file solve our problem, thanks, 
but were does this file come from ?
Which version of the magiclib it is please ? 
Thanks 
Franck

**Comment by DaGaMs** [comment]
I don't remember, to be honest. I might have re-generated the file myself, actually, after fixing the incorrect regex.

**Comment by mscdex** [comment]
Please try the master branch, I have merged in libmagic 5.32 now.

**Comment by mscdex** [comment]
I've published v0.4.6.

**Pull request closed without merging**
